### ISSUE TITLE
(SUGGESTION) Make it so you can see the menu without being in a level

### ISSUE THREAD

**Issue by sevenfootrat** [decoder0007/PosBot#10]
So you can change modes and load macro before entering a level. Every bot with a separate tab does that.
![image](https://user-images.githubusercontent.com/107514826/174418063-2c88f1d1-b639-49d8-bdd7-6688d5509591.png)

**Comment by sevenfootrat** [comment]
Also add rerecording (record where you left off)
And choose what variables gets changed on replay

**Comment by Skyue1** [comment]
what version of vs are you using??

**Comment by sevenfootrat** [comment]
what?

**Comment by Skyue1** [comment]
just copy this repository and remove the part of the code where the part is located so that the menu opens without going into the level

**Comment by sevenfootrat** [comment]
idk how to do that

**Comment by Decoder0007** [comment]
Please don’t do that it will undoubtedly crash. I don’t see why this is an issue but fine I’ll make it show in the next update
