### ISSUE TITLE
The spider is not supposed to do that...

### ISSUE THREAD

**Issue by Hartemis888** [decoder0007/PosBot#11]
Hi, for quite a long time, g this weird bug, and I thought it was going to be fixed in the new update. 
Anyway, here is the video of the bug (sorry for the crappy quality and the watermark) 
thanks in advance :

[https://youtu.be/4qvMx-aNgQI](https://youtu.be/4qvMx-aNgQI)

**Comment by sevenfootrat** [comment]
happens to me too

**Comment by Decoder0007** [comment]
Lol what I have never seen that before. Probably something to do with gravity will fix.
