### ISSUE TITLE
Clicks Are Doubled

### ISSUE THREAD

**Issue by Tommeeboi** [decoder0007/PosBot#13]
Recently, PosBot (v1.5) has been acting strange. I recorded Abyss Of Darkness, but when I went into playback mode, every single click that I did was a double click for some reason. This has been happening to every macro I've recorded since then. I have Dual Click turned off btw. I tried removing Run-Info but that did nothing. I even tried removing the imgui.ini file in the PosBot folder but it did nothing. I am certain that it isn't my mouse, because when I've recorded these macros, my Mega Hack click counter says I'm clicking once, but when I play the macro it says I'm clicking twice. MHv7 created a crashlog if you want that

**Comment by Decoder0007** [comment]
Sorry for the late reply. This is a known bug that has been fixed please check closed issues before creating a duplicate.
