### ISSUE TITLE
Animation follows practice mode

### ISSUE THREAD

**Issue by RewardedIvan** [decoder0007/PosBot#15]
![bug](https://user-images.githubusercontent.com/67065165/213531990-e14b678e-feb2-4af1-b64d-e30ea69c60e8.mp4)
I have GDHM installed, but that shouldn't affect anything (P.S. My CPS doubles for some reason).
Placing a checkpoint while a yellow pad is doing its thing, will cause the animation to be weird in the playback.  
The playback animation is following the animation in practice mode. Basically when you respawn it cancels the yellow pad animation and that shouldn't be the case in playback mode.
This also works with orbs.

**Comment by Decoder0007** [comment]
Fixed in latest update
