### ISSUE TITLE
Frame Advance not working?

### ISSUE THREAD

**Issue by xperyi** [decoder0007/PosBot#16]
Everything is working as intended but when I toggle Frame Advance on, it doesn't do anything, I pressed my keybind for Frame Advance but nothings happening. Am I doing something wrong ???

**Comment by Decoder0007** [comment]
What other mods are you using

**Comment by TobyAdd** [comment]
decoder didn't even make frame advance, this is made purely for show

**Comment by TobyAdd** [comment]
Decoder didn't even make it. It's just a checkbox that does nothing

**Comment by Decoder0007** [comment]
Does work skill issue
