### ISSUE TITLE
This is a virus

### ISSUE THREAD

**Issue by WaveyDeimC** [decoder0007/PosBot#2]
Don't recommend. 1. Sometimes doesn't detect when I go in a level 2. After recording a macro and setting the speed to 1, it glitches and plays the macro at approximately 2.175894676845675867875857475756786867867958 speed

**Comment by Decoder0007** [comment]
How can you call it a virus when the source code it right there

**Comment by WaveyDeimC** [comment]
I have different terms of the word virus. When something looks malicious, then it's a virus. Also I have a problem after downloading this. One of the backgrounds is now about 1.5x brighter than normal. It's really distracting.

**Comment by WaveyDeimC** [comment]
> I have different terms of the word virus. When something looks malicious, then it's a virus. Also I have a problem after downloading this. One of the backgrounds is now about 1.5x brighter than normal. It's really distracting.

ok i managed to fix it

**Comment by Decoder0007** [comment]
But… the source code it right there. You cannot call it a virus until you
or someone else has checked through it.
