### ISSUE TITLE
Macro is played incorrectly... very incorrectly

### ISSUE THREAD

**Issue by tahiadz1962** [decoder0007/PosBot#20]
so incorrect the music was done before the level was
so incorrect i had to use noclip
https://drive.google.com/file/d/11SBxjFAI7NXu2BCmLYGX91jXor9zSXwA/view?usp=sharing

**Comment by Decoder0007** [comment]
Download latest version

**Comment by tahiadz1962** [comment]
that is what i did

**Comment by Decoder0007** [comment]
No ur on an old version

**Comment by Decoder0007** [comment]
Also make sure you use posbots speedhack and fps bypass. Disable lock delta, real time, smooth fix. Uninstall replaybot

**Comment by tahiadz1962** [comment]
ok

**Comment by tahiadz1962** [comment]
anyways is there a click pack you recommend?

**Comment by Decoder0007** [comment]
In the release section

**Comment by tahiadz1962** [comment]
that one sounds like popcorn in an oven

**Comment by tahiadz1962** [comment]
i cant find the compiled release of plombore 1.7, can you send me the compiled link?

**Comment by Decoder0007** [comment]
It’s under the release section of the GitHub
https://decoder0007.github.io/

**Comment by tahiadz1962** [comment]
![Capture](https://user-images.githubusercontent.com/79606983/226134060-f8f01395-c48a-4aef-9b9c-24023dad7c26.PNG)
then this is what i see

**Comment by Decoder0007** [comment]
Click it then click tags then click v1.7

**Comment by tahiadz1962** [comment]
oh
