### ISSUE TITLE
Can't bind a key

### ISSUE THREAD

**Issue by zenezenez** [decoder0007/PosBot#23]
When i click on the button to bind a key it says "Waiting for keypress..." and doesnt do anything when i press keys.

**Comment by Decoder0007** [comment]
what other mods do you have installed

**Comment by zenezenez** [comment]
alt tab fix, betteredit, betterinfo, circle tool, editor line limit bypass, every key jumps (tried deleting this one and still didnt work), geometry cache, input lag
also im using gdhm not mh if that matters
