### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by andr3i1010** [decoder0007/PosBot#3]
If I enter a level, it keeps saying "Head into a level to start!".
Can someone fix this for me?

Thanks.

**Comment by Decoder0007** [comment]
Download latest version

**Comment by andr3i1010** [comment]
@decoder0007 already did

**Comment by Decoder0007** [comment]
What other mods do you have installed?

**Comment by andr3i1010** [comment]
gdshare
invisible dual bugfix
run info
betterinfo
betteredit
Mega Hack v7
(my mods)

**Comment by andr3i1010** [comment]
nvm i fixed it with deleting mods

**Comment by Decoder0007** [comment]
It’s run info
