### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by ghost** [decoder0007/PosBot#5]
Alright i'll explain it quick....

When i bot a level, i go and bot it in practice etc. But when i replay the macro, i die where i didn't die when i was botting the level.

example: I botted Slaughterhouse for 4K60FPS showcase, i didn't die on 46%, but when i replayed the macro, i did die there.

lmk if you don't understand something, i could explain it more.

**Comment by Decoder0007** [comment]
Yeah the latest version of PosBot is not good. If you want rerecord on 1.3
it’s 100% accurate

**Comment by ghost** [comment]
oh, thanks for the quick response, alright i'll use 1.3, have a nice rest of the day
