### ISSUE TITLE
Double click at replay

### ISSUE THREAD

**Issue by sasas991** [decoder0007/PosBot#8]
I recorded a macro with posbot. And cps in the replay is double(for example: 1 cps while recording. 2 cps in the replay)

**Comment by Aldiyar991** [comment]
Uploading 2022-06-13 18-16-09.mp4…

**Comment by IFoodstampZ** [comment]
Don't use cps counter for botting, the code for cps counter is based off of some fucky use of framerate.

**Comment by Decoder0007** [comment]
No it’s my fault
